### ISSUE TITLE
PAL version missing

### ISSUE THREAD

**Issue by hellocatfood** [ex-zee-ex/waaaave_pool#1]
In the readme the link to the PAL version returns a 404 error https://drive.google.com/open?id=1wFxnRCTPwVjB3DsjzN7t_d5pV1JQVEvo

**Comment by ex-zee-ex** [comment]
ah thanks for that, i'll get that image back up in 24 hours

**Comment by ex-zee-ex** [comment]
https://drive.google.com/open?id=1NRAtnwgg4Qb_DpktbGL0417CbcAsfyYt its live
again

**Comment by hellocatfood** [comment]
Thanks!
