### ISSUE TITLE
Feature request: update diagram

### ISSUE THREAD

**Issue by hellocatfood** [ex-zee-ex/waaaave_pool#2]
I have recreated the diagram of the Korg nanoKONTROL so that it is a bit easier to read. 

![rect1218](https://user-images.githubusercontent.com/151947/77258975-13a8ed00-6c76-11ea-88e6-d4b003aca63a.png)
(Original from here https://github.com/hellocatfood/nanoKONTROL-illustration )

Can this be used in the readme?

**Comment by ex-zee-ex** [comment]
oh thanks!  i actually had a better graphic already over on the larger
waaave pool manual page
https://andreijaycreativecoding.com/Waaave_Pool-manual so i just merged a
bunch of the infos over into the github

**Comment by hellocatfood** [comment]
Ah, that looks better already! Well, the vector file is there should you want to use that at any point instead.

**Comment by ex-zee-ex** [comment]
thanks much!
